repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: detect-private-key
      # - id: pretty-format-json
      #   args:
      #   - --autofix
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--line-length=120"]
      - id: black-jupyter
        args: ["--line-length=120"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort
        additional_dependencies: [isort>=5.13.0, black==24.3.0]
        args:
          [
            "--profile=black",
            "--float-to-top",
            "--multi-line=3",
            "--line-width=80",
            "--use-parentheses",
            "--trailing-comma",
            "--force-grid-wrap=0",
          ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        args: ["--line-length=120"]
        additional_dependencies: [black==24.3.0]

      - id: nbqa-isort
        args: [
            "--profile=black",
            # "--float-to-top",
            "--multi-line=3",
            "--line-width=80",
            "--use-parentheses",
            "--trailing-comma",
            "--force-grid-wrap=0",
          ]
        additional_dependencies: [isort>=5.13.0, black==24.3.0]
