
name: "finbert"
platform: "ensemble"
max_batch_size: 16
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [3]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "finbert-tokenizer"
      model_version: -1
      input_map {
        key: "text"
        value: "text"
      }
      output_map {
        key: "input_ids"
        value: "input_ids"
      }
      output_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      output_map {
        key: "token_type_ids"
        value: "token_type_ids"
      }
    },
    {
      model_name: "finbert-model"
      model_version: -1
      input_map {
        key: "input_ids"
        value: "input_ids"
      }
      input_map {
        key: "attention_mask"
        value: "attention_mask"
      }
      input_map {
        key: "token_type_ids"
        value: "token_type_ids"
      }
      output_map {
        key: "logits"
        value: "logits"
      }
    }
  ]
}
