name: "simple_net"
platform: "pytorch_libtorch"
backend: "pytorch"
max_batch_size: 0
input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [2]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
